# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 12b5661cedfa6a487a31b896e7c39ab4462b62d0279603915f0514e4477c3a2a28de8705f6d64578750809692db251c8927ae490475dfaf543e239fa31663604

test:
  secret_key_base: 1a4f82ad9567955e2293a08fb93e778b9a6d75999e7b1733db4fe3efbdc883b23e7d06f90a3c9d946d30bcbc9649f0d695b3776c0f873055056e0af35f3a7615

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
